spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: apigateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity
              uri: lb://identity
              predicates:
                - Path=/api/v1/user/**,/api/v1/role/**,/api/v1/permission/**,/api/v1/auth/**
            - id: employee
              uri: lb://employee
              predicates:
                - Path=/api/v1/employee/**,/api/v1/position/**
            - id: scrum
              uri: lb://scrum
              predicates:
                - Path=/api/v1/project/**,/api/v1/board-column/**,/api/v1/work-item/**,/api/v1/sprint/**,/api/v1/board/**,/api/v1/payment/**
            - id: reporting
              uri: lb://reporting
              predicates:
                - Path=/api/v1/reporting/**
          discovery:
            locator:
              enabled: true
          globalcors:
            cors-configurations:
              "[/**]":
                allowedOrigins:
                  - "http://${CORS_HOST:localhost}:${CORS_PORT:80}"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - Authorization
                  - Content-Type
                  - Accept
                  - Origin
                allowCredentials: false
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST

server:
  port: ${PORT:8000}
  forward-headers-strategy: framework

security:
  jwt:
    secret: ${JWT_SECRET:secretkey}
    issuer: ${JWT_ISSUER:sprintforge-identity}

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 15
    ip-address: ${PUBLIC_HOST:localhost}
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:${EUREKA_PORT:8761}/eureka/
